package CovariantReturnType;

    /*
    The clone method overriding in a Person class.
    This is a valid override of Object's clone method.

    @Override
    protected Object clone() throws CloneNotSupportedException {
        return super.cone();
    }

    The clone method(generated by Intellij) override (from Object)
     */

public class Person {
    private String name;
    private String birthDate;

    public Person(String name, String birthDate) {
        this.name = name;
        this.birthDate = birthDate;
    }

    @Override
    public Person clone() {
        return new Person(name, birthDate);
    }
}
